Factory.define :event do |event|
  event.title("This is a test event")
  event.start_date_time(1.day.from_now)
  event.end_date_time(2.days.from_now)
  event.description("This is going to be HUGE!")
  event.address_line_1("23 Tall Skey")
  event.city("Dallas")
  event.state("TX")
  event.postal_code(75206)
  event.registration_fee(100.00)
  event.minimum_age_to_participate(18)
  event.minimum_age_to_register(18)
  event.latitude(95.02)
  event.longitude(-36.45)
  event.time_zone('Central Time (US & Canada)')
  event.event_state(:registration_closed)
end